server:
  port: 8005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  application:
   name: identity-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/



