spring:
  application:
    name: api-gateway

  cloud:
    gateway:
#      default-filters:
#        - name: JwtAuthFilter

      routes:
      - id: product-service
        uri: http://localhost:9095
        predicates:
        - Path=/api/v1/products/**
        filters:
          - TokenRelay

      - id: orderservice
        uri: http://localhost:9094
        predicates:
          - Path=/api/v1/order/**
        filters:
          - TokenRelay

      - id: discoveryserver
        uri: http://localhost:8762
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/

      - id: discoveryserver-static
        uri: http://localhost:8762
        predicates:
          - Path=/eureka/**

      - id: identity-service
        uri: http://localhost:8005
        predicates:
          - Path=/api/v1/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8005
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      defaultZone: http://localhost:8762/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE


server:
  port: 9091
