spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka


server:
  port: 9094